### ISSUE TITLE
Index out of bounds error every pulse

### ISSUE THREAD

**Issue by csmith** [DMDirc/dmdirc3#203]
Sending lots of messages, the entire client locked up and this happened:

```
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 3
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.sun.javafx.collections.ObservableListWrapper.get(ObservableListWrapper.java:89)
	at com.sun.javafx.collections.VetoableListDecorator.get(VetoableListDecorator.java:306)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1701)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1645)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.computeLocalBounds(Node.java:3853)
	at javafx.scene.Node.updateLocalBounds(Node.java:3883)
	at javafx.scene.Node.getLocalBounds(Node.java:3753)
	at javafx.scene.Node.updateTxBounds(Node.java:3901)
	at javafx.scene.Node.getTransformedBounds(Node.java:3693)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1634)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.updateTxBounds(Node.java:3901)
	at javafx.scene.Node.getTransformedBounds(Node.java:3693)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1706)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1645)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.updateTxBounds(Node.java:3901)
	at javafx.scene.Node.getTransformedBounds(Node.java:3693)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1634)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.updateTxBounds(Node.java:3901)
	at javafx.scene.Node.getTransformedBounds(Node.java:3693)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1706)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1645)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.updateTxBounds(Node.java:3901)
	at javafx.scene.Node.getTransformedBounds(Node.java:3693)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
	at javafx.scene.Parent.updateCachedBounds(Parent.java:1706)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1645)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.updateTxBounds(Node.java:3901)
	at javafx.scene.Node.getTransformedBounds(Node.java:3693)
	at javafx.scene.Parent.getChildTransformedBounds(Parent.java:1845)
	at javafx.scene.Parent.recomputeBounds(Parent.java:1634)
	at javafx.scene.Parent.doComputeGeomBounds(Parent.java:1498)
	at javafx.scene.Parent.access$200(Parent.java:79)
	at javafx.scene.Parent$1.doComputeGeomBounds(Parent.java:115)
	at com.sun.javafx.scene.ParentHelper.computeGeomBoundsImpl(ParentHelper.java:84)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBoundsImpl(RegionHelper.java:78)
	at com.sun.javafx.scene.layout.RegionHelper.superComputeGeomBounds(RegionHelper.java:62)
	at javafx.scene.layout.Region.doComputeGeomBounds(Region.java:3289)
	at javafx.scene.layout.Region.access$300(Region.java:147)
	at javafx.scene.layout.Region$1.doComputeGeomBounds(Region.java:168)
	at com.sun.javafx.scene.layout.RegionHelper.computeGeomBoundsImpl(RegionHelper.java:89)
	at com.sun.javafx.scene.NodeHelper.computeGeomBounds(NodeHelper.java:115)
	at javafx.scene.Node.updateGeomBounds(Node.java:3837)
	at javafx.scene.Node.getGeomBounds(Node.java:3799)
	at javafx.scene.Node.getLocalBounds(Node.java:3747)
	at javafx.scene.Node.intersectsBounds(Node.java:5282)
	at javafx.scene.Node$1.intersectsBounds(Node.java:548)
	at com.sun.javafx.scene.NodeHelper.intersectsBounds(NodeHelper.java:262)
	at javafx.scene.layout.Region.doPickNodeLocal(Region.java:3158)
	at javafx.scene.layout.Region.access$600(Region.java:147)
	at javafx.scene.layout.Region$1.doPickNodeLocal(Region.java:184)
	at com.sun.javafx.scene.layout.RegionHelper.pickNodeLocalImpl(RegionHelper.java:104)
	at com.sun.javafx.scene.NodeHelper.pickNodeLocal(NodeHelper.java:128)
	at javafx.scene.Node.pickNode(Node.java:5192)
	at javafx.scene.Scene$MouseHandler.pickNode(Scene.java:3993)
	at javafx.scene.Scene$MouseHandler.access$1300(Scene.java:3579)
	at javafx.scene.Scene.pick(Scene.java:2029)
	at javafx.scene.Scene.access$6800(Scene.java:172)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3805)
	at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
	at javafx.scene.Scene$MouseHandler$1.run(Scene.java:3615)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It then repeated every single pulse, 60 times a second...

**Comment by csmith** [comment]
Might be the same cause as #201 which is now fixed

**Comment by csmith** [comment]
Haven't seen it again.
